name: Removal Request
description: Request removal of a listed project.
title: "[Removal]: Project Name"
labels: ["removal"]
body:

  - type: input
    id: repo_url
    attributes:
      label: Repository URL
      placeholder: https://github.com/user/repo
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason for Removal
      description: Explain why the project should be removed.
    validations:
      required: true

  - type: checkboxes
    id: ownership
    attributes:
      label: Ownership Confirmation
      options:
        - label: I confirm that I am the owner or authorized representative of this project.
          required: true
